name = "FASF"
author = "OGBillyLoomis"
version = "0.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7c9b35b33f480ce1d1fae2be5302f798cfcb487251e21bc36202933b3f7e9f8d"

[versions]
forge = "47.1.3"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
