name = "FASF"
author = "OGBillyLoomis"
version = "0.0.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5315800aa23bba341faee88ee989055d591518beabea3076a4e858956e4f105d"

[versions]
forge = "47.1.3"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
