name = "FASF"
author = "OGBillyLoomis"
version = "0.0.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d3eb9189a6d68dcd2127f6de6f572e9a3c9ebe481421a9f50951c3201dbc6cf5"

[versions]
forge = "47.1.3"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
