name = "FASF"
author = "OGBillyLoomis"
version = "0.0.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ddb453483c5873e4517e9dbc47172170c07d58272be197ce49756b9c7e4d3758"

[versions]
forge = "47.1.3"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
