name = "FASF"
author = "OGBillyLoomis"
version = "0.0.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6d3d031fb4d85df119cf3641b69f8c6f03c7780c04a291500de27608a44713b3"

[versions]
forge = "47.1.3"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
