name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19

    - name: Install packwiz
      run: go install github.com/packwiz/packwiz@latest

    - name: Build and Export
      run: packwiz curseforge export

    - name: Find zip artifact
      id: findzip
      run: |
        zipfile=$(ls *.zip | head -n 1)
        echo "::set-output name=zipfile::$zipfile"

    - name: Upload Release Artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ steps.findzip.outputs.zipfile }}
        path: ${{ steps.findzip.outputs.zipfile }}
        if-no-files-found: error
