name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19

    - name: Install packwiz
      run: go install github.com/packwiz/packwiz@latest

    - name: Build and Export
      run: packwiz curseforge export

    - name: Find zip artifact
      id: findzip
      run: |
        zipfile=$(ls *.zip | head -n 1)
        echo "::set-output name=zipfile::$zipfile"

    - name: Upload Release Artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ steps.findzip.outputs.zipfile }}
        path: ${{ steps.findzip.outputs.zipfile }}
        if-no-files-found: error
        
    - name: Release
      uses: softprops/action-gh-release@91409e712cf565ce9eff10c87a8d1b11b81757ae
      if: startsWith(github.ref, 'refs/tags/')
      with:
        # Identify if this is a pre release by checking if the tag name contains -rc, -b, -a
        prerelease: ${{ contains(github.ref, '-rc') || contains(github.ref, '-b') || contains(github.ref, '-a') }}
        files: ${{ steps.findzip.outputs.zipfile }}
      env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
